# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:6

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_OPTS: --insecure-registry=gitlab-registry.kubernetes.knmi.nl
  
# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
stages:
  - dependencies
  - build
  - test
  - docker
  - deploy

npm_install:
  stage: dependencies
  cache:
    paths:
      - node_modules/
  script:
    - npm install yarn
    - yarn install
  artifacts:
    paths:
      - node_modules/
    expire_in: 20 minutes

npm_build:
  stage: build
  dependencies:
    - npm_install
  script:
    - npm run build
  artifacts:
    paths:
      - build/
   
run_test:
  stage: test
  dependencies:
    - npm_install
  script:
    - npm test
  coverage: /^All files *\|[^|]*\|[^|]*\|[^|]*\| *(\d+.\d+)|/
  artifacts:
    paths:
      - coverage/

docker_build:
  stage: docker
  image: docker:latest
  services:
    - jonasknmi/dind-options:latest
  dependencies:
    - npm_build
  variables:
    CONTAINER_IMAGE_URL: $CI_REGISTRY_IMAGE/demo-frontend:$CI_COMMIT_SHA
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CONTAINER_IMAGE_URL .
    - docker push $CONTAINER_IMAGE_URL

deploy_review:
  stage: deploy
  image: jonasknmi/envsubst-kubectl:1.6.4
  dependencies:
    - docker_build
  variables:
    ENVIRONMENT_HOSTNAME: $CI_ENVIRONMENT_SLUG.demo-review.kubernetes.knmi.nl
    CONTAINER_IMAGE_URL: $CI_REGISTRY_IMAGE/demo-frontend:$CI_COMMIT_SHA
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.demo-review.kubernetes.knmi.nl
    on_stop: stop_review
  script:
    - env
    - cat deployment.yaml | envsubst > deployment-env.yaml
    - kubectl apply -f deployment-env.yaml -n $CI_ENVIRONMENT_SLUG
  only:
    - branches
  except:
    - master

stop_review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - kubectl delete namespace $CI_ENVIRONMENT_SLUG
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop

deploy_staging:
  stage: deploy
  image: jonasknmi/envsubst-kubectl:1.6.4
  dependencies:
    - docker_build
  variables:
    ENVIRONMENT_HOSTNAME: demo-staging.kubernetes.knmi.nl
    CONTAINER_IMAGE_URL: $CI_REGISTRY_IMAGE/demo-frontend:$CI_COMMIT_SHA
  environment:
    name: staging
    url: http://$ENVIRONMENT_HOSTNAME
  script:
    - env
    - cat deployment.yaml | envsubst > deployment-env.yaml
    - kubectl apply -f deployment-env.yaml -n $CI_ENVIRONMENT_SLUG
  only:
    - master

deploy_production:
  stage: deploy
  image: jonasknmi/envsubst-kubectl:1.6.4
  dependencies:
    - docker_build
  variables:
    ENVIRONMENT_HOSTNAME: demo.kubernetes.knmi.nl
    CONTAINER_IMAGE_URL: $CI_REGISTRY_IMAGE/demo-frontend:$CI_COMMIT_SHA
  environment:
    name: production
    url: http://$ENVIRONMENT_HOSTNAME
  script:
    - env
    - cat deployment.yaml | envsubst > deployment-env.yaml
    - kubectl apply -f deployment-env.yaml -n $CI_ENVIRONMENT_SLUG
  when: manual
  only:
    - master
   
pages:
  stage: deploy
  dependencies:
    - run_test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
