# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:6

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
  
stages:
  - prebuild
  - build
  - test
  - deploy
  
npm_install:
  stage: prebuild
  script:
    - npm install yarn
    - yarn install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
   
test:
  stage: test
  script:
    - npm test
  coverage: /^All files *\|[^|]*\|[^|]*\|[^|]*\| *(\d+.\d+)|/
  artifacts:
    paths:
      - coverage/

deploy:
  dependencies:
    - build
  stage: deploy
  script:
    - find build
   
pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv coverage/lcov-report public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master