apiVersion: v1
kind: Namespace
metadata:
  name: $CI_ENVIRONMENT_SLUG
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $CI_ENVIRONMENT_SLUG
  namespace: $CI_ENVIRONMENT_SLUG
  labels:
    app: $CI_ENVIRONMENT_SLUG
    track: stable
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: $CI_ENVIRONMENT_SLUG
        track: stable
    spec:
      containers:
      - name: demo-frontend
        image: demo-frontend:$CI_BUILD_REF_NAME
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: $CI_ENVIRONMENT_SLUG
  namespace: $CI_ENVIRONMENT_SLUG
  labels:
    app: $CI_ENVIRONMENT_SLUG
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: $CI_ENVIRONMENT_SLUG
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $CI_ENVIRONMENT_SLUG
  namespace: $CI_ENVIRONMENT_SLUG
  labels:
    app: $CI_ENVIRONMENT_SLUG
    pipeline_id: "$CI_PIPELINE_ID"
    build_id: "$CI_BUILD_ID"
spec:
  rules:
  - host: $ENVIRONMENT_HOSTNAME
    http:
      paths:
      - path: /
        backend:
          serviceName: $CI_ENVIRONMENT_SLUG
          servicePort: http
